#!/usr/bin/env python3
"""Regenerate simple Markdown indexes from note metadata."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from validate_metadata import parse_simple_yaml


DOMAIN_ORDER = [
    "mathematics",
    "physics",
    "statistics",
    "probability",
    "data-science",
    "machine-learning",
    "artificial-intelligence",
    "computer-science",
    "quantitative-finance",
    "other",
]

DOMAIN_LABELS = {
    "mathematics": "Mathematics",
    "physics": "Physics",
    "statistics": "Statistics",
    "probability": "Probability",
    "data-science": "Data Science",
    "machine-learning": "Machine Learning",
    "artificial-intelligence": "Artificial Intelligence",
    "computer-science": "Computer Science",
    "quantitative-finance": "Quantitative Finance",
    "other": "Other",
}


def as_list(value: object) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    if isinstance(value, str) and value.strip():
        return [value.strip()]
    return []


def collect_notes(notes_root: Path) -> list[dict[str, object]]:
    notes: list[dict[str, object]] = []
    for metadata_path in sorted(notes_root.glob("*/*/metadata.yaml")):
        data = parse_simple_yaml(metadata_path)
        data["_metadata_path"] = metadata_path
        data["_note_dir"] = metadata_path.parent
        notes.append(data)
    return notes


def note_link(kb_root: Path, note: dict[str, object]) -> str:
    note_dir = Path(str(note["_note_dir"]))
    target = note_dir / "README.md"
    if not target.exists():
        target = note_dir
    return Path("..") / target.relative_to(kb_root.parent)


def note_bullet(kb_root: Path, note: dict[str, object]) -> str:
    title = str(note.get("title", "Untitled"))
    summary = str(note.get("summary", "")).strip()
    link = note_link(kb_root, note).as_posix()
    if summary:
        return f"- [{title}]({link}) - {summary}"
    return f"- [{title}]({link})"


def write_domain_index(kb_root: Path, notes: list[dict[str, object]]) -> None:
    by_domain: dict[str, list[dict[str, object]]] = defaultdict(list)
    for note in notes:
        by_domain[str(note.get("domain", "other"))].append(note)

    lines = [
        "# Domain Index",
        "",
        "Generated by `scripts/update_index.py`. Curated maps of content remain manual.",
        "",
    ]
    for domain in DOMAIN_ORDER:
        lines.append(f"## {DOMAIN_LABELS[domain]}")
        lines.append("")
        items = by_domain.get(domain, [])
        if items:
            lines.extend(note_bullet(kb_root, note) for note in items)
        else:
            lines.append("_No notes yet._")
        lines.append("")
    (kb_root / "domain-index.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_tag_index(kb_root: Path, notes: list[dict[str, object]]) -> None:
    by_tag: dict[str, list[dict[str, object]]] = defaultdict(list)
    for note in notes:
        for tag in as_list(note.get("tags", [])):
            by_tag[tag].append(note)

    lines = ["# Tag Index", "", "Generated by `scripts/update_index.py`.", ""]
    if not by_tag:
        lines.append("_No tags indexed yet._")
    for tag in sorted(by_tag):
        lines.extend([f"## `{tag}`", ""])
        lines.extend(note_bullet(kb_root, note) for note in by_tag[tag])
        lines.append("")
    (kb_root / "tag-index.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_concept_index(kb_root: Path, notes: list[dict[str, object]]) -> None:
    by_concept: dict[str, list[dict[str, object]]] = defaultdict(list)
    for note in notes:
        for concept in as_list(note.get("concepts", [])):
            by_concept[concept].append(note)

    lines = ["# Concept Index", "", "Generated by `scripts/update_index.py`.", ""]
    if not by_concept:
        lines.append("_No concepts indexed yet._")
    for concept in sorted(by_concept, key=str.lower):
        lines.extend([f"## {concept}", ""])
        lines.extend(note_bullet(kb_root, note) for note in by_concept[concept])
        lines.append("")
    (kb_root / "concept-index.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def write_main_index(kb_root: Path, notes: list[dict[str, object]]) -> None:
    lines = [
        "# Knowledge Base Index",
        "",
        f"Generated index for {len(notes)} final note(s).",
        "",
        "## Main Indexes",
        "",
        "- [Domain Index](domain-index.md)",
        "- [Concept Index](concept-index.md)",
        "- [Tag Index](tag-index.md)",
        "- [Prerequisite Map](prerequisite-map.md)",
        "- [Learning Paths](learning-paths.md)",
        "",
        "## Maps Of Content",
        "",
        "- [Linear Algebra](maps-of-content/linear-algebra.md)",
        "- [Probability](maps-of-content/probability.md)",
        "- [Optimization](maps-of-content/optimization.md)",
        "- [Classical Mechanics](maps-of-content/classical-mechanics.md)",
        "- [Neural Networks](maps-of-content/neural-networks.md)",
        "- [Algorithms](maps-of-content/algorithms.md)",
        "- [Statistical Inference](maps-of-content/statistical-inference.md)",
        "",
        "## Recently Indexed Notes",
        "",
    ]
    if notes:
        lines.extend(note_bullet(kb_root, note) for note in sorted(notes, key=lambda item: str(item.get("updated_at", "")), reverse=True)[:20])
    else:
        lines.append("_No notes yet._")
    (kb_root / "index.md").write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--notes", default="notes", help="Root notes directory.")
    parser.add_argument("--knowledge-base", default="knowledge-base", help="Knowledge-base directory.")
    args = parser.parse_args()

    notes_root = Path(args.notes)
    kb_root = Path(args.knowledge_base)
    kb_root.mkdir(parents=True, exist_ok=True)

    notes = collect_notes(notes_root)
    write_main_index(kb_root, notes)
    write_domain_index(kb_root, notes)
    write_tag_index(kb_root, notes)
    write_concept_index(kb_root, notes)
    print(f"Indexed {len(notes)} note(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

